### ISSUE TITLE
not working with latest EDK

### ISSUE THREAD

**Issue by rafisv** [Salvoxia/info_links#1]
Same as with the top kills... box is checked in modules and cache was refreshed but nothing showing up

**Comment by Salvoxia** [comment]
Hi,

does the box in ACP -> Modules stay checked when clicking save? And is the folder named _info_links_ or _info_links-1.0_ ?

Best Regards,
Salvoxia

**Comment by rafisv** [comment]
Default installation  folder  "info_links/info_links". Fixed by moving. Thanks a lot.
